# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73f0c53bf635e0089e6783b84ac1d6e1e739e9868de98302d0af9ba7e9718f391f985bccb3a0116a7731c40a1b05206e9bc85ab2ca8622f99e20a4838b21d47e

test:
  secret_key_base: ee5ec00adb947aeb2f6ea041cfc729a053ffffc137393ec3d90cf3f209b010befbb3693b5862d5e1199f4e36d6111cb257ebb7907ac71823bdfa4066835a4965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
